USE [master]
GO

/****** Object:  Database [Contactos]    Script Date: 09/01/2023 16:34:23 ******/
CREATE DATABASE [Contactos]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Contactos', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Contactos.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Contactos_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Contactos_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Contactos].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Contactos] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Contactos] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Contactos] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Contactos] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Contactos] SET ARITHABORT OFF 
GO

ALTER DATABASE [Contactos] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Contactos] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Contactos] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Contactos] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Contactos] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Contactos] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Contactos] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Contactos] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Contactos] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Contactos] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Contactos] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Contactos] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Contactos] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Contactos] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Contactos] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Contactos] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Contactos] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Contactos] SET RECOVERY FULL 
GO

ALTER DATABASE [Contactos] SET  MULTI_USER 
GO

ALTER DATABASE [Contactos] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Contactos] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Contactos] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Contactos] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Contactos] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Contactos] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Contactos] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Contactos] SET  READ_WRITE 
GO


